version: "3.8"
services:
    nginx:
        image: nginx:1.20
        container_name: nginx-csv
        links:
            - php-csv
        volumes:
            - ./nginx:/etc/nginx/conf.d:delegated
            - ../:/var/www/html/csv:delegated
        ports:
            - "80:80"
        working_dir: /var/www/html/csv
        networks:
            csv_network:
                ipv4_address: 172.18.0.2
    php-csv:
        working_dir: /var/www/html/csv
        build:
            context: ./
            dockerfile: php/php.Dockerfile
        image: php8.2-csv
        container_name: php-csv
        volumes:
            - ../:/var/www/html/csv:delegated
        networks:
            csv_network:
                ipv4_address: 172.18.0.4
    redis:
        image: redis:6.2.5-alpine
        container_name: redis-csv
        ports:
            - "6379:6379"
        networks:
            csv_network:
                ipv4_address: 172.18.0.7
    mysql:
        image: mariadb:10.6.10
        container_name: csv-db
        restart: "on-failure"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: csv
        ports:
            - "3306:3306"
        volumes:
            - csv-mysql-data:/var/lib/mysql
        networks:
            csv_network:
                ipv4_address: 172.18.0.3

volumes:
    csv-mysql-data:
        external: true

networks:
    csv_network:
        name: csv_network
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
